/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1018567_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1018567_1[] = { "extension", "fist", "rest", "rock", "snap" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1018567_2_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_1018567_2_axes_size = 2;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1018567_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    2, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1018567_2[26] = { 6.0985435092449185, -0.2882948393840343, 6.210462515801192, 2.252057139724493, 3.5187859457731245, 2.103965935409069, 1.6168401479721068, 1.3392421326041222, 1.1186771497130394, 1.0390895256400108, 0.9788817867636681, 0.944774551987648, 1.0159691178798675, 7.825607081651688, 0.03733410962857306, 2.3489408924616875, 2.3619559979438782, 3.8004008171707393, 1.9400706535577774, 1.6239023613929748, 1.3228631526231767, 1.1106601071357727, 0.998971047103405, 0.9728167575597763, 0.9426553845405579, 1.026067328453064 };
const float ei_dn_standard_scaler_scale_1018567_2[26] = { 0.287316385502163, 0.43455111060489515, 0.02137558067033405, 1.9523841734738974, 0.804185844791116, 1.231078583501418, 1.660541131177049, 1.808578430298512, 1.9632138903045107, 2.212967502952072, 2.2790119514409852, 2.33762389104631, 2.497970191088305, 0.198457816151918, 0.6843260007301845, 0.03924036714192078, 2.88933876598598, 1.0216539059172405, 1.619168354546487, 2.0462170551703767, 2.299000707644962, 2.5501684127090543, 2.58121060376704, 2.594384901299749, 2.703618562066666, 2.7730078262852067 };
const float ei_dn_standard_scaler_var_1018567_2[26] = { 12.113766871169211, 5.295637776855095, 2188.58872511711, 0.26234297730828227, 1.5462764841317302, 0.6598245157250406, 0.362660891777464, 0.3057210243088869, 0.2594566245156844, 0.20419726793556842, 0.1925337167160489, 0.18299984656446308, 0.160260132309136, 25.390051626518467, 2.1353738383755516, 649.4322866019701, 0.11978517480525694, 0.9580593211841483, 0.38143099906393113, 0.2388342460210932, 0.18920028667440408, 0.15376669353096478, 0.15009047046065077, 0.14857002062139937, 0.13680726509127075, 0.1300462428049594 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1018567_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1018567_2,
    .mean_data_len = 26,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1018567_2,
    .scale_data_len = 26,
    .var_data = (float *)ei_dn_standard_scaler_var_1018567_2,
    .var_data_len = 26
};
ei_data_normalization_t ei_data_normalization_config_1018567_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1018567_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1018567_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1018567_1[ei_dsp_blocks_1018567_1_size] = {
    { // DSP block 2
        2,
        26, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1018567_2, // pointer to config struct
        ei_dsp_config_1018567_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1018567_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1018567_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1018567_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1018567_3_init,
    .model_invoke = &tflite_learn_1018567_3_invoke,
    .model_reset = &tflite_learn_1018567_3_reset,
    .model_input = &tflite_learn_1018567_3_input,
    .model_output = &tflite_learn_1018567_3_output,
};

const uint8_t ei_output_tensors_indices_1018567_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1018567_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1018567_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1018567_3,
    .output_tensors_size = ei_output_tensors_size_1018567_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1018567_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1018567_1_size = 1;
const uint32_t ei_learning_block_1018567_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_1018567_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1018567_1[ei_learning_blocks_1018567_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1018567_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1018567_3_inputs,
        ei_learning_block_1018567_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1018567_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1018567_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1018567_1[ei_postprocessing_blocks_1018567_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1018567_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1018567_1_size = 0;

uint32_t *freeform_outputs_1018567_1 = nullptr;

const ei_impulse_t impulse_1018567_1 = {
    .project_id = 1018567,
    .project_owner = "amirfrf",
    .project_name = "EMG sensors 2 channels Hoan hand",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 26,
    .raw_sample_count = 500,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 500 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 2,
    .frequency = 500,

    .dsp_blocks_size = ei_dsp_blocks_1018567_1_size,
    .dsp_blocks = ei_dsp_blocks_1018567_1,

    .learning_blocks_size = ei_learning_blocks_1018567_1_size,
    .learning_blocks = ei_learning_blocks_1018567_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1018567_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1018567_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "a0 + a1",
    .slice_size = (500/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 5,
    .categories = ei_classifier_inferencing_categories_1018567_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1018567_1_size,
    .freeform_outputs = freeform_outputs_1018567_1
};

ei_impulse_handle_t impulse_handle_1018567_1 = ei_impulse_handle_t( &impulse_1018567_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1018567_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1018567_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1018567_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1018567_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
