/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 06.06.2026 09:02:40

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1440;
#else
constexpr int kTensorArenaSize = 416;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,26 } };
const TfArray<1, float> quant0_scale = { 1, { 0.025073565542697906, } };
const TfArray<1, int> quant0_zero = { 1, { 64 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[5] = { 640, -426, -999, 746, 31, };
const TfArray<1, int> tensor_dimension1 = { 1, { 5 } };
const TfArray<1, float> quant1_scale = { 1, { 8.1641825090628117e-05, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[5*32] = { 
  58, -49, -36, 55, -113, 8, 75, -97, 69, 13, -1, -79, -119, 103, -10, -89, 29, -40, 55, 65, 59, -47, 35, -85, -46, -101, -78, -48, -61, 42, -98, 21, 
  43, 98, 37, -31, -100, 79, -58, 65, 41, 34, -97, -26, 2, 39, -80, -18, -85, 64, 55, -17, 1, -101, -114, 71, 28, 45, 91, -92, -104, -33, -43, -34, 
  -89, -36, -72, -80, -103, 61, 78, 17, 35, 9, 91, 20, 35, -40, -71, 87, 90, -60, 20, 55, -113, 62, -116, 66, 21, -111, 56, 53, 15, 16, 15, -15, 
  17, 117, -104, 71, -1, -14, -60, -69, -46, -55, -28, 42, 127, 39, 7, 72, 77, -74, -114, -68, -73, 70, 52, 6, -81, 7, -91, 75, -71, -1, -99, 64, 
  57, -100, -117, 46, -104, 20, 61, -103, -31, 83, 4, 94, -51, -30, -118, 84, -91, 18, -69, -12, 84, 73, -117, 56, -64, 48, 61, -58, 66, -119, -14, -82, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 5,32 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0044889636337757111, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[32] = { 984, 1023, 196, 1404, 1648, -310, 37, -577, 1032, -370, -512, 1273, 1334, 1247, 1670, 6, 272, 137, 364, -526, 738, -156, 1531, -309, -229, 1171, 245, 877, 621, 1008, 718, 876, };
const TfArray<1, int> tensor_dimension3 = { 1, { 32 } };
const TfArray<1, float> quant3_scale = { 1, { 6.1053673562128097e-05, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[32*64] = { 
  51, 92, 18, 10, -21, -9, -45, 75, 32, 30, -42, 71, -7, 59, 61, 23, -33, 7, -25, 68, -1, 94, 85, 41, -47, -88, -40, 45, 68, -17, -45, 4, 78, 16, 15, 95, 19, -59, -38, 18, 38, -35, 16, 18, 25, -52, 70, 32, -45, -69, 67, 60, 50, 4, -36, 15, 78, 41, 7, -11, 34, 76, 38, -46, 
  -51, -23, -44, 9, -69, -16, 62, 69, 85, 28, -27, 18, 40, 18, -86, 69, 23, 76, -9, 50, 81, -42, 15, -57, -62, 38, 56, -19, -57, 27, 35, -12, -26, 87, 38, -106, -23, 21, -91, -17, -30, -22, -53, 72, 43, 88, 52, -59, 65, 29, 80, 39, -59, -31, -43, 15, 26, -52, 23, 61, 22, -95, 45, 21, 
  -41, -30, -40, 37, 72, 88, 70, 32, -22, 27, 11, 76, 95, -37, -48, 94, 24, 36, 58, -44, 4, 53, 81, -39, -11, -26, -44, -101, -77, 67, 90, 56, 4, -39, -95, -101, 61, -63, -61, 24, -34, -82, -33, -40, -23, 44, 92, 56, -47, -58, 66, -1, 17, 46, 2, -48, -89, 43, -46, -83, -19, 11, -103, 49, 
  81, 63, 84, -50, -3, -34, -11, -24, -52, -4, 45, 71, 46, 26, 11, -44, -13, -83, -13, 29, -24, 98, -27, 90, 61, 36, 38, 18, -54, -21, -38, 17, -13, 76, 78, 47, -18, 72, 52, -66, 47, 92, -65, 33, -32, 81, -45, 55, 25, 41, 27, 31, 36, 26, 50, -41, 104, 19, 2, 13, -26, 80, -13, -34, 
  -38, -33, -100, 41, -96, -41, -67, 42, 59, 85, -52, -7, -22, -8, 30, 52, -5, -39, -39, -31, 12, 15, 93, 77, -32, -72, -18, -13, -35, -10, -18, -57, 23, -14, 126, -87, -64, 57, 26, 61, -97, 86, 103, 100, 78, 102, -1, -71, -49, -47, -90, -48, -29, 18, 28, 45, 6, -2, 16, -46, 97, 4, -43, -42, 
  -58, 35, -20, -37, -63, -25, 51, -67, -47, 33, -1, -52, -27, -7, 31, -34, -66, 8, 41, 45, 28, -16, -75, 10, 15, -58, -68, -21, 6, -55, 13, 13, 21, -42, -24, -56, 5, -33, 54, -19, -62, -39, -21, 66, -6, -56, -73, -36, 4, 57, -18, 18, -69, -21, 55, 22, 12, -48, 15, 30, 61, -65, 42, -14, 
  76, 62, -9, 5, 53, 51, -10, 4, -43, -25, 3, -62, -53, 108, -50, -29, 68, -65, 61, 12, 6, 71, 15, 65, 94, 73, -28, -1, 87, -55, 30, 18, -65, 20, -22, 34, 59, -36, 11, -73, -54, -70, -32, -88, -74, 61, 27, 29, -41, 102, 55, -7, 98, 105, 63, -19, -21, 67, 34, 62, 36, 16, 80, -64, 
  -36, -28, -103, 80, 51, 77, 70, 58, 27, -58, 81, 75, 25, 1, 35, 46, -2, 46, -59, 43, -50, -36, 14, -75, -63, 20, 22, -28, -60, 13, 64, -80, -42, 11, -70, 13, 65, -54, 47, -47, 43, -29, -64, 34, 20, 57, -14, 7, 64, -47, -15, -33, -38, -22, -2, 29, -9, 41, -54, -82, 45, -21, 0, -59, 
  44, 96, 15, 72, -15, -20, 89, -45, 3, 67, 48, -28, 45, 103, -1, 86, 32, 36, 50, -55, -83, -49, 53, 44, 4, 77, 65, 58, 62, 63, 66, 1, 76, -80, 19, 33, 8, -32, 19, 11, -13, -105, -71, 53, 3, -11, 52, -6, 53, 14, 3, -2, -13, 79, 18, 11, -30, -2, -58, -36, -70, -43, -56, -5, 
  71, 30, 21, 34, -36, -7, 57, -17, 10, -47, -29, -3, -25, -43, -11, 0, -33, 53, 7, -59, -43, 68, -22, 21, -33, -12, 11, -32, 35, -12, -35, -46, -22, -86, 6, 5, 11, 64, -46, -70, -10, -41, 2, -67, -38, -57, 1, 66, 60, 21, 64, 23, 19, 13, 29, 71, 50, -7, -37, 43, 39, 93, 19, 62, 
  -59, -10, 31, 28, -46, -7, -42, -65, -52, -21, -38, -39, 6, 5, 16, 48, 56, 56, 4, 54, 12, -72, 12, -60, 58, -6, 54, 67, -62, 67, 8, -30, -55, -46, -9, 61, 2, -9, 67, 75, 24, -67, -7, 5, -55, 66, -83, 84, 41, 85, 42, 51, 64, -38, 43, 7, 51, 68, -43, -58, 43, -70, 62, -2, 
  -23, -32, 98, -35, -31, -3, 56, 2, -14, -59, -86, -32, 45, 30, 76, 24, -30, -101, -26, -15, 21, 9, -91, 62, 6, 51, 40, -40, 43, 12, -14, -83, -24, -38, -52, 81, 37, 69, 60, 26, -38, -30, 9, -14, -18, 24, -12, 75, -44, 0, -58, -5, 8, 47, 0, -20, 100, 71, -55, 103, 30, 21, 70, 77, 
  -82, -58, -47, 84, 27, -71, -80, -43, 67, 57, 31, -24, -46, -24, 10, -5, 53, -24, 32, 26, 33, 41, 27, 26, -28, -44, 0, -36, -45, 50, -2, -8, 100, 92, 81, -44, 46, -15, -45, 76, -48, 3, 48, 93, 44, 22, -54, -7, -84, 34, -60, -7, -69, -93, 31, -30, 6, 11, -48, 53, -31, -38, 70, 54, 
  4, 41, -78, -20, 37, -9, -118, -39, -31, 102, 102, -77, 12, 61, 42, 33, -3, -66, -3, 60, -38, 36, 73, 26, -10, -74, -24, -57, 13, 57, 44, 9, 18, 1, 54, -41, 53, -40, -14, -31, -42, 34, -41, 70, -22, 4, 62, 105, -39, 56, 22, 43, 65, -7, 118, -9, 66, -88, -47, -1, -17, 80, -46, -48, 
  40, 80, -7, 29, -34, 68, -41, 51, 60, 36, 41, 7, 84, 8, -102, 29, 71, 19, 78, 116, -20, -5, 29, -26, 18, -13, -25, -18, -61, 34, 57, 30, 43, 57, 39, -39, -18, -10, 67, -32, 26, -19, -24, -25, -8, 127, 72, 43, 35, 56, -80, 63, 53, -8, 91, -43, 74, -39, -40, -2, -7, -35, 11, -51, 
  51, -16, 47, -49, 21, 26, -12, -9, -57, 40, -82, 9, 23, 32, 33, -32, -28, 35, -54, 19, 53, 82, 24, -4, 0, -11, -41, 60, 40, 74, 17, -43, 65, 95, -68, -9, -41, 35, 12, 84, 52, 30, 76, 56, -51, 87, -22, 48, -73, 29, -7, -1, 20, -28, -25, 55, 27, 31, 0, 85, 27, -2, 81, 7, 
  11, 80, -33, 29, 32, 1, -2, -83, 22, 56, -12, -11, 47, 69, -34, -87, -1, 10, 38, -44, 52, 13, 68, -56, 38, 8, 56, 29, 17, -5, -8, -19, 54, 29, 28, -14, -20, -32, -35, 71, -62, -1, 40, 104, 3, -6, -46, -44, -2, -14, 13, 60, 65, -42, -49, 83, 55, 41, -54, 10, -33, -22, 16, -74, 
  72, 19, -31, 42, -35, -1, 104, 96, 34, -86, -53, 29, 22, -38, -28, 5, 62, 21, 2, -62, 32, -34, 66, 4, -39, -82, 40, -67, -15, -25, 65, -53, -64, -2, -79, -49, 32, -20, -66, 38, 15, 4, 49, -77, -15, -33, 19, 21, -50, -88, 32, 53, 43, 26, 2, 54, -11, 52, 11, -15, 76, 45, 6, 95, 
  18, 37, -53, 46, 11, 68, -35, 91, 47, -24, 40, 2, 71, 28, 8, 78, 86, -14, 24, -66, -67, -12, 42, -53, 26, 28, 60, -19, 46, 64, 20, 77, -34, -11, -50, -83, -30, -61, 73, 26, 90, -41, -56, -8, -26, 26, -33, -21, 83, 22, 14, 16, -41, 81, 36, 36, -4, -12, 45, -49, -22, 51, 20, 43, 
  -49, 14, -34, 29, -7, 71, -61, 5, -13, -14, 14, 9, -43, 52, -62, 4, -11, -19, 58, 50, -2, 21, -11, 41, 25, 8, 41, 6, -32, -31, -67, 108, -19, -92, -26, 24, 70, -79, -9, 13, -48, -55, 49, 50, -48, 50, 86, 2, 25, 21, 7, 43, 30, 58, 68, -40, 47, -66, -59, 9, -53, 11, 57, 29, 
  -4, -5, -12, 18, -36, -40, 47, -9, 51, -22, 88, 32, -43, 26, 68, -20, 70, -27, 102, 4, -30, 50, 2, 18, -2, 1, -46, -63, 22, -5, -10, 100, 51, -62, -20, 102, -31, -49, 49, 5, 83, -36, -57, -16, -47, -15, 18, 32, -20, -29, 76, 25, 45, 93, 15, -75, -59, 51, -14, 76, 8, 93, 43, 27, 
  48, 33, -29, 50, 58, -49, 25, -44, 49, 26, -15, 29, 36, -11, 7, -83, 0, 13, 27, 61, 52, 89, 8, 31, 43, 51, 56, -2, 43, 50, -62, -58, 21, 90, 34, 3, 34, -27, 56, 16, -60, 95, 34, 61, 60, 14, -102, -72, -43, 53, -36, 55, 37, -32, 5, -39, 56, -13, -49, 58, 8, 44, 40, -59, 
  -4, 76, -36, 35, -75, -52, -61, 49, -74, 78, 38, -72, 3, 3, 0, -14, 6, -78, 84, 42, 89, -44, 39, 89, -14, -88, 43, -36, -28, -16, 2, 103, 22, 108, 4, -67, -47, -38, -43, 21, -60, 81, -12, -4, -34, 30, 80, 10, -39, 75, 16, 21, 23, 90, 9, 55, 53, -82, -30, -23, 65, -14, -29, -67, 
  67, -88, 84, 49, 76, 72, 93, 70, 29, -21, 16, 57, 70, -74, -1, 37, 59, 79, 42, 21, 2, 14, -48, 74, -66, 46, -19, 52, -15, 22, 45, 7, -16, -23, -1, 51, -12, -61, 44, 28, 19, -41, 78, -80, 44, -94, 5, -72, 11, -21, 76, 38, -63, 53, -29, -54, 46, 36, -39, 33, 94, -64, 61, -40, 
  -75, 22, -33, 69, -14, 71, 34, 101, -1, 23, 39, 23, -45, -2, -47, -21, 68, 29, 22, 21, -26, -6, 69, 20, -88, 0, 61, -21, -51, -38, -13, 14, 14, 6, -76, -79, -35, -62, 28, -38, 47, 26, 73, -39, 36, 31, -42, 9, -4, -61, 22, 23, -59, -64, 6, 86, -81, 10, 32, 3, 21, 11, 61, -39, 
  -19, 35, 82, 68, -13, -23, 90, 60, -13, 52, 25, 99, 85, -76, 95, 61, -27, -34, -20, -21, 57, 38, 56, -16, 67, 13, 13, 2, 9, -8, 42, 31, 16, -3, 40, 13, 1, -46, -11, 6, -6, 19, -35, 61, -53, -33, -4, -86, 1, -46, 72, 72, -82, -75, -5, -39, 6, 97, 16, 5, 6, 52, 31, 98, 
  -10, -2, -5, 1, -41, 10, -7, 52, 17, 21, 24, 102, 34, 51, 67, 60, -48, -7, -82, 62, 75, 25, 30, -13, -21, 52, -42, 1, 61, -26, 96, -52, -28, -36, -62, -33, 9, -13, 75, -54, 88, -24, 36, -105, -9, -26, 8, 14, 9, -64, 56, 75, 11, -51, 54, 90, -32, 46, 16, -13, -23, 57, -14, -32, 
  7, 48, 23, -33, -9, 26, -77, 36, 3, 50, -47, -26, 75, -34, -46, -75, 24, 36, -51, -37, -21, -3, -22, -59, -39, 86, 11, -5, 6, 32, -6, -61, -50, 103, 20, 30, -26, 23, 78, -40, -13, 43, -8, -16, 49, 33, 18, -20, -51, 93, -41, 78, 29, -43, 54, 74, 9, -29, 11, 55, 30, -94, -22, -5, 
  98, 108, 35, -23, -41, -39, 59, -22, 50, -18, -81, 59, -61, -28, 71, 14, -13, -49, -68, -36, 16, 22, -50, 68, -25, -36, -17, 32, -3, 0, 16, -60, -34, -41, -112, 32, 23, 0, 23, 19, -15, 61, 46, -103, 37, -16, -90, 87, -48, -17, -46, 35, -46, 5, -21, -39, -21, 26, 33, 6, 26, 62, -11, -17, 
  -28, 0, 42, -3, 51, 28, -76, -40, 16, 22, -23, 25, 30, -31, -59, 0, 47, -42, 114, 77, -69, -83, 20, 45, 33, 65, 32, -22, 1, 24, -36, 42, 96, 10, 47, 10, 59, 49, 54, 21, 76, -20, 44, 13, -48, -3, 62, 80, 33, 5, -33, 54, 73, 34, 63, 94, 11, -15, 53, 31, -26, 19, -52, -27, 
  35, -22, 77, -32, 85, 33, 16, -34, -61, 52, -41, -53, -16, -13, 85, -72, 79, 42, -8, 2, 39, -24, 32, 35, 52, -14, 90, -37, -23, -41, -27, -13, 23, -33, 9, 66, 77, -10, 7, -61, 21, 1, 57, -66, 30, -11, -78, 42, 51, -39, 28, -43, -54, -58, 34, 69, -6, 87, 18, -37, -17, 11, 73, 76, 
  9, -11, -64, 62, -15, -3, -65, 34, -44, -13, 0, 23, -1, -22, 42, 21, -39, 4, 96, 72, 7, -69, 58, -22, -25, -69, -62, 67, -17, 97, -70, -7, 51, 11, 58, 19, 3, -39, 40, 48, -64, 65, 35, 48, 18, 63, 21, 59, -85, 59, -55, 16, 20, 78, -23, 24, 5, 0, -17, 34, 2, -66, -46, -5, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 32,64 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0034085758961737156, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[64] = { 568, 1101, 397, 311, 582, -416, 1299, 632, 384, 763, 451, 879, 336, 757, 847, -218, 146, -473, 1302, 478, 995, 720, 874, 496, 289, 249, 374, -398, 401, 465, 190, 1088, 975, 1393, 1622, 524, -517, 1064, -246, -23, 102, 1290, 439, 964, -162, 1158, 683, 1018, -290, 414, 194, 574, 1166, 764, 375, 487, 1032, 871, -761, 927, 559, 1140, -236, 555, };
const TfArray<1, int> tensor_dimension5 = { 1, { 64 } };
const TfArray<1, float> quant5_scale = { 1, { 9.0445188106968999e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[64*26] = { 
  32, -25, -41, 53, 36, 19, -18, 76, -29, -31, 44, -25, -33, 48, 41, -61, 78, 64, 61, -48, 13, 78, -34, 34, -27, -8, 
  -97, 30, -94, 36, -5, 34, -19, -14, -95, -29, 36, -92, -24, 63, 9, -22, 14, -18, 77, 37, 14, 73, -53, -30, -62, -35, 
  89, -18, 6, 30, -54, 40, 72, -29, -33, -29, 50, 62, -39, 84, 46, 13, 79, 72, 10, -39, -20, 42, 44, -47, 67, 22, 
  -80, 27, 84, 24, 50, -62, 60, 50, -4, 11, 50, -75, 10, -69, -33, 37, -28, 55, 10, -69, -77, -51, -57, 57, -80, 7, 
  30, 14, -57, -79, -64, 12, -14, -72, -49, -87, 40, -45, -84, -34, 57, -21, -79, -56, -41, -49, -15, 27, -23, 37, 33, 36, 
  -32, -44, -30, -14, 10, -84, -56, -33, -63, -71, 40, 9, 46, -55, -43, 16, 44, 41, -88, 28, -51, -38, -58, 62, -54, -49, 
  77, -127, -61, 10, 73, -10, 35, -21, -56, -38, 14, 63, 57, -16, 10, -34, -9, -18, -52, -55, -7, -6, -8, -50, 11, 27, 
  55, -51, 1, 73, 69, -7, 19, -74, 2, 32, 16, -18, 12, -75, -87, -55, 59, 39, -77, 10, 13, -36, -66, -17, 49, 62, 
  37, -57, -22, 17, -10, 43, -6, 20, -25, -56, -11, 42, -42, -77, -73, -47, -50, 2, 69, -59, -19, 12, -43, -5, -37, -30, 
  -55, 29, -44, -45, 33, 15, -4, -34, 9, 84, -33, 36, 69, 33, -107, 40, 49, 36, 61, -53, 10, 34, 63, -8, -30, 48, 
  47, -13, -52, -33, 62, -10, -70, -68, 51, 8, -74, -68, -62, -78, -93, 30, 43, 56, 16, -2, -1, 48, 46, -18, 40, -47, 
  21, -105, 11, 90, 61, -19, 59, 61, -40, 2, 19, 20, -4, -26, -21, -79, 18, 58, -48, -45, 21, -66, -79, -7, 13, 8, 
  -37, -37, -43, -25, -31, 16, -15, 9, 61, -64, -59, -35, -50, -98, -20, -15, -13, 41, 41, -28, -19, -50, -61, 21, -40, 7, 
  -11, 84, 0, -52, -4, -95, -67, -43, -6, 8, -81, 40, -45, -24, -70, 53, -25, -55, 58, -24, 69, 27, -36, -65, -8, -51, 
  102, -81, 22, 20, -31, -50, 42, -26, 79, 73, -14, 70, -47, 10, 101, -91, -32, -28, 65, 11, 9, -69, -89, -4, -58, 12, 
  -23, -73, 95, -10, 73, 1, 15, -55, -23, 16, -19, 26, 42, 32, -59, -43, 20, -67, 21, 36, -23, -60, -34, -7, 32, -45, 
  -21, 13, -22, 1, 35, -76, 41, -36, 32, -37, 33, -63, 24, -60, -33, -8, 34, 75, -17, -61, -57, 66, 19, -30, 56, -3, 
  -9, -62, 95, -71, 9, -50, -3, -34, 14, 8, 7, -47, 42, -74, -51, -37, -14, 25, -88, -34, -47, 21, -21, 2, -24, -43, 
  -92, 64, 18, -19, 103, -24, 42, 13, -55, -41, -69, -91, 48, 25, 32, -88, 21, 26, 46, 53, 58, 1, 39, -30, 4, -14, 
  -10, 27, 7, 53, 20, 22, -29, 15, 59, -37, 74, 80, -14, 63, -68, -23, -4, -35, 22, -32, -40, -49, 4, 64, 20, 67, 
  2, -29, -76, -14, 34, 77, 16, 55, 24, 67, -38, -2, 26, -51, -51, -80, -47, 42, 12, 77, -27, -72, -30, 20, 22, 0, 
  27, -25, -35, 34, 72, 52, -39, 93, -38, -20, 82, 64, 25, 90, -5, -18, 55, 45, 66, -67, 10, 47, 28, 12, -52, -92, 
  -47, -68, 4, 84, -35, 36, -42, 17, -16, -74, -63, -83, 3, -99, -58, -37, -47, 77, 46, -39, 14, -67, 9, 50, -3, -57, 
  65, 81, -61, 6, 10, -17, 73, 31, -24, 78, -18, 2, 50, 52, -16, 19, 13, 68, -27, 45, -45, -35, -16, 9, -74, 29, 
  13, -45, -84, -67, -21, 47, 61, 40, -16, 19, -61, -58, -53, 21, -16, 35, 84, -55, 44, 11, 47, 41, -36, 54, -3, -79, 
  27, -23, 59, -47, 19, -13, -45, -55, -62, -39, -61, 17, -50, 44, 42, 48, -81, -40, -46, -50, -17, -67, -40, 23, 5, 24, 
  -35, -46, 15, -77, -54, -54, -75, 33, -18, -50, -23, -36, -81, -57, -53, -23, -19, -51, -39, -20, 5, 29, -46, -70, -31, 31, 
  -62, -57, 22, -70, 16, -39, -14, 39, -44, -26, -57, -42, 63, 8, 12, 44, 10, -52, -68, 46, 5, -26, 40, -16, 32, -61, 
  107, 27, -82, 38, -36, -28, 34, -14, -44, 41, 2, 58, 4, 10, 103, 11, -43, -38, 57, 36, -65, -12, -21, -52, -34, -61, 
  21, 86, 49, 27, 8, 47, -50, 73, 57, -16, -1, 36, -57, 36, -75, -65, -59, -60, -62, 46, -20, 2, -34, 59, 37, 75, 
  3, -37, 15, 28, 47, -11, 53, 34, 26, 32, -20, -67, -40, -46, 36, 28, 22, -50, -49, 31, -103, -33, 47, -58, 9, -46, 
  -1, -41, -37, 86, -16, -47, -90, -84, 22, -6, -52, -24, -27, 87, -1, -33, 82, -4, 24, 56, 65, 31, 30, 2, -54, 33, 
  -77, 103, -1, 25, 20, -7, -47, -55, 57, 45, 69, 26, 38, -41, -47, 43, 6, 84, 54, 73, 29, -9, -56, 24, -51, 25, 
  -76, 99, -4, -6, -29, 21, 67, 65, 23, -9, -43, 92, 3, -49, -1, 5, 88, -47, 31, -19, 78, 0, 29, -53, -83, 53, 
  -85, 93, 27, 11, 43, 45, -7, 38, -30, -53, 67, 45, 65, -37, -44, -76, 61, 35, -8, 50, 82, -23, -24, 20, 2, 12, 
  102, -8, -6, 90, -3, 38, -17, 68, 18, 19, 47, -57, -58, 101, 73, 36, -32, -30, -33, -4, 39, -49, -58, -23, 27, -67, 
  -34, 14, -18, 47, -20, -31, -16, -20, -7, -25, -39, 51, 10, -31, 76, -14, -26, 34, -37, -69, 11, -15, 44, -50, -54, 69, 
  38, 44, -68, -39, -8, 38, 9, 77, 34, 35, 33, 2, 56, 11, -14, 3, -7, 42, 54, -5, 47, -32, 29, -60, 22, -53, 
  -44, -12, -21, 3, -89, -70, -93, -52, -45, 48, -80, -26, -29, -25, -14, -55, -14, -7, -29, -45, -30, -18, -21, 62, 17, 24, 
  48, 72, -23, 59, 27, -51, 37, -3, 53, 28, -43, -53, 4, -10, -60, 2, -82, -74, -52, 22, 3, -60, -12, 23, 65, 4, 
  0, -86, 6, -49, -6, -39, 64, 33, -32, 21, -71, -67, -50, -51, 53, -13, -13, 15, 26, -53, -25, -25, 6, -79, -63, -30, 
  51, -15, -80, 35, -40, 102, -35, 103, 82, 8, 64, -24, 38, -66, -20, -103, -5, 60, 21, 50, 81, 14, 40, -70, 34, -13, 
  -76, -51, -23, -90, -75, -16, -6, 45, -86, 16, -33, 18, 12, 31, 81, 31, 34, -56, -70, -62, 4, -55, -31, 22, -6, 8, 
  -55, 64, 29, 26, -9, 57, -18, 46, 0, -36, 53, 39, 52, -76, -109, -77, 6, 28, 70, -27, 58, 58, -41, 59, -64, 72, 
  -11, 62, -43, -28, 56, -11, 40, 28, 51, 13, -35, 57, -8, 41, 39, 44, -59, -64, -55, -34, -22, -23, 37, 54, 61, 50, 
  -11, 82, -35, 76, -36, 0, 61, -22, 36, 65, 18, 62, 80, -53, -96, 29, -62, 15, -18, 14, -6, 16, 38, 17, 50, -19, 
  -56, -61, 26, -2, 75, 65, 23, -100, -29, 23, -63, -73, -85, 17, -94, -62, 14, 81, 60, 0, -88, 10, 52, 7, -63, -19, 
  -2, -38, -1, 85, 14, -74, -42, -10, -44, 15, -46, -9, 24, 79, -48, -70, 52, 90, 82, 58, 32, 3, 38, 10, 70, 8, 
  29, -79, 40, -70, 31, 60, 33, 14, -58, -61, -61, -64, -7, -75, 20, -55, 5, -19, 17, 63, 55, 55, -33, 54, -25, -45, 
  -87, 105, 9, -11, -25, 35, -77, -53, -40, -28, 32, -31, -71, 48, -59, 28, -28, 61, -25, -62, -51, 64, 19, -15, 22, -51, 
  64, -88, 8, -29, 16, 18, 76, -40, -41, -63, 76, 25, -59, 7, -17, -22, 0, -32, 38, -60, -92, 18, 49, -72, -51, 3, 
  69, 11, 38, 50, -52, 71, 67, 0, 68, 68, 23, -61, -49, 52, -75, -68, 75, 52, 63, -57, 38, 30, -25, -36, 22, -68, 
  -20, 16, -89, -34, -20, 50, -56, 20, -80, -85, 31, -83, -20, 47, -31, 16, -37, 68, -48, -23, 59, 71, -22, -28, 72, 38, 
  -57, 0, 44, -52, 75, -72, -48, 8, -48, -32, -31, -59, -51, 40, 27, 5, 64, 82, 42, 73, 77, 7, -3, -2, 49, -47, 
  -66, 10, -18, 5, -36, 24, 42, -40, 43, -74, -28, -67, 20, -27, -69, -22, -37, 15, -34, 56, 72, 70, 54, 29, 79, -73, 
  -68, -49, -58, -38, 19, 15, -73, 16, -78, -33, -16, 0, 30, -1, -2, 22, 15, -78, -72, -37, -14, -63, -60, -30, 6, 13, 
  -23, 65, 3, 46, 52, 66, 85, 40, 83, 41, -12, 13, 50, -48, 39, -26, -39, 73, 80, 70, 31, 20, 22, -52, -53, -53, 
  98, -17, -12, -58, -35, 60, 62, -10, -4, -56, 14, 25, 20, -33, 87, -51, 16, 18, -70, -77, -28, 41, -67, 40, -60, -89, 
  33, 25, 25, 1, -44, -55, 24, -22, 35, -49, 58, 27, 1, -8, -22, 24, 22, 45, 3, 41, 41, 9, 39, 36, 19, 49, 
  32, 34, 20, 56, 63, -12, -23, 100, 84, -3, 22, 32, 41, -11, 18, -10, 45, 77, 90, -25, 16, 27, 8, 15, 29, -7, 
  84, 40, -29, 28, 36, -23, -6, 57, 57, 3, 37, 20, -37, -78, -50, -79, -2, 52, -21, -6, 9, -85, -71, -29, -1, 5, 
  43, -21, -110, 93, 7, -47, -14, 53, -21, -41, -16, 23, 20, 65, 114, -36, 68, 45, 31, 38, -83, 38, -23, -67, -71, -30, 
  -49, -26, 30, -75, -52, 27, -31, -10, 49, -30, -22, -57, -9, -33, 24, -9, 15, -38, -14, 39, -52, 3, -28, -26, 35, 1, 
  63, -15, -13, -14, -2, 38, -44, 14, -25, 1, 4, 38, 29, 28, 14, -11, -5, 5, -8, 7, -87, -62, -56, -47, -55, -41, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 64,26 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00360719277523458, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,64 } };
const TfArray<1, float> quant7_scale = { 1, { 0.01791178435087204, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,32 } };
const TfArray<1, float> quant8_scale = { 1, { 0.018187232315540314, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,5 } };
const TfArray<1, float> quant9_scale = { 1, { 0.069441705942153931, } };
const TfArray<1, int> quant9_zero = { 1, { -18 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 26, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 2048, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1664, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension8, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1018567_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1018567_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1018567_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1018567_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1018567_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
